server:
  port: 8080

spring:
  application:
    name: matchmaking

  datasource:
    url: jdbc:mysql://localhost:3306/GameDB
    username: root
    password: 741852963Abqs
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true

  main:
    web-application-type: servlet

